version: '{build}'
image: Visual Studio 2017
environment:
  ANDROID_HOME: "C:\\android-sdk-windows"
  ANDROID_NDK_HOME: "C:\\android-sdk-windows\\ndk-bundle"
  ANDROID_BUILD_VERSION: 29
  ANDROID_TOOLS_VERSION: 29.0.3
  ANDROID_NDK_VERSION: 20.0.5594570
  ANDROID_CMAKE_VERSION: 3.10.2.4988404
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  SDK_TOOLS_URL: https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip
install:
  - mkdir "%ANDROID_HOME%"
  - appveyor DownloadFile "%SDK_TOOLS_URL%" -FileName "%TMP%/sdk-tools.zip"
  - 7z x "%TMP%/sdk-tools.zip" -o"%ANDROID_HOME%" > nul
  - set PATH=%PATH%;"%ANDROID_HOME%\tools\bin"
  - yes 2> nul | sdkmanager --licenses > nul
  - yes 2> nul | sdkmanager "platform-tools" "platforms;android-%ANDROID_BUILD_VERSION%" > nul
  - yes 2> nul | sdkmanager "ndk;%ANDROID_NDK_VERSION%" > nul
  - yes 2> nul | sdkmanager "cmake;%ANDROID_CMAKE_VERSION%" > nul
cache:
  - "%USERPROFILE%\\.gradle\\caches"
  - "%USERPROFILE%\\.gradle\\wrapper"
  - "%USERPROFILE%\\.m2\\repository"
build_script:
  - cmd: gradlew.bat clean cleanBuildCache build bintrayUpload -PbintrayUser=dryUser -PbintrayKey=dryKey
artifacts:
  - path: '**\libs\*sentry*.jar'
  - path: '**\outputs\aar\*sentry*release*.aar'
  - path: '**\publications\**\pom-default.xml'
  - path: '**\publications\**\module.json'
on_finish:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      Get-ChildItem . -Name -Recurse 'TEST-*.xml'  |
      Foreach-Object {
          $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_))
      }
