sudo: false
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager --update
install:
  - echo y | sdkmanager "ndk;21.0.6113669" >/dev/null
  - echo y | sdkmanager "cmake;3.10.2.4988404" >/dev/null
before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
  - chmod +x ./gradlew
script:
- make all
android:
  components:
    - platform-tools
    - build-tools-29.0.3
    - android-29
os: linux
dist: trusty
language: android
matrix:
  include:
    - jdk: openjdk8
      after_success:
        - bash <(curl -s https://codecov.io/bash)
