name: SDK Size Analysis

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Analyze SDK Size
    runs-on: ubuntu-latest

    env:
      GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Java Version
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "17"

      # Workaround for https://github.com/gradle/actions/issues/21 to use config cache
      - name: Cache buildSrc
        uses: actions/cache@v4
        with:
          path: buildSrc/build
          key: build-logic-${{ hashFiles('buildSrc/src/**', 'buildSrc/build.gradle.kts','buildSrc/settings.gradle.kts') }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Size Analysis
        run: ./gradlew :sentry-android-integration-tests:test-app-size:bundleRelease
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
